### ISSUE TITLE
SOAP.py

### ISSUE THREAD

**Issue by D-XH** [wenbohuang1002/SOAP#1]
大佬，你模型文件是空的，什么时候能放出来？

**Comment by wenbohuang1002** [comment]
其实早就准备好了，只不过有些讨厌的人在准备人肉爬虫我的账号（参考我的copyright）。你如果需要的话，我今天就上传些权重文件，足够你复现了。最近在开题，实在有些忙不过来了。

**Comment by D-XH** [comment]
好的，多谢大佬

**Comment by wenbohuang1002** [comment]
已经上传至此仓库的release中，仅供学习用途。此issue关闭。
