### ISSUE TITLE
复现过程中，CHEM的问题

### ISSUE THREAD

**Issue by D-XH** [wenbohuang1002/SOAP#2]
在复现的过程中，发现论文中CHEM部分先对空间进行卷据平均池化，这时H和W都是1，再进行2D卷积。而在权重文件中发现这个2D的卷积核尺寸是3，如果按论文中来是没法进行卷积的，而且没有找到1D卷积的权重。这里应该怎么处理？
![s2](https://github.com/user-attachments/assets/c8fda8a0-d916-4854-9ecd-4a448d885e1a)
![s](https://github.com/user-attachments/assets/7b610cb5-cc6c-45a9-a88c-a802f2674110)

**Comment by wenbohuang1002** [comment]
这两个2D就不是用在这里的。其实这里只要能把通道数改变，你用一个线性层替代也是完全没有问题的，参考SE就可以。

**Comment by wenbohuang1002** [comment]
我当时用的1×1的2D在这里，权重里应该有才对

**Comment by D-XH** [comment]
好的，我看间ch1和ch2，我就以为是CHEM里的两个2D卷积。但是1D卷积确实没找到，我再找找看

**Comment by D-XH** [comment]
那这两个2D应该是哪的呢？HMEM里的吗

**Comment by wenbohuang1002** [comment]
没有的话你可以自己写一写，没有必要完全按照我的来。

**Comment by wenbohuang1002** [comment]
这里的你提问的池化操作你可以当做为了减少计算量才用的，我文中阐述也有写，你的计算资源充足可以不用这个。毕竟都是我九个月前写的代码了，你这样在假期里事无巨细的问又秒回，每天人忘记的事情有那么多，一个计算一个计算的，我一时半会也不能飞回学校再重新整理一遍给你，你说是不。

**Comment by D-XH** [comment]
ok，感谢大佬的回答
